// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwR8UWwFI0onvSaaSSGAVDX2Z1S33eWk',
    appId: '1:80359379857:web:aa3b83d7c1007e3ba74030',
    messagingSenderId: '80359379857',
    projectId: 'my-pomodoro-b5569',
    authDomain: 'my-pomodoro-b5569.firebaseapp.com',
    storageBucket: 'my-pomodoro-b5569.firebasestorage.app',
    measurementId: 'G-SV7MBZD9MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjvcaQ3HQEun2iHayvBe3KZ9kgJv8rsM',
    appId: '1:80359379857:android:6d8867433c70356ea74030',
    messagingSenderId: '80359379857',
    projectId: 'my-pomodoro-b5569',
    storageBucket: 'my-pomodoro-b5569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-GvP62lGow0Vus9yFapU2Y1F6rkiURE',
    appId: '1:80359379857:ios:ae4f5832d893b253a74030',
    messagingSenderId: '80359379857',
    projectId: 'my-pomodoro-b5569',
    storageBucket: 'my-pomodoro-b5569.firebasestorage.app',
    iosBundleId: 'com.example.flutterPomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN-GvP62lGow0Vus9yFapU2Y1F6rkiURE',
    appId: '1:80359379857:ios:ae4f5832d893b253a74030',
    messagingSenderId: '80359379857',
    projectId: 'my-pomodoro-b5569',
    storageBucket: 'my-pomodoro-b5569.firebasestorage.app',
    iosBundleId: 'com.example.flutterPomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBwR8UWwFI0onvSaaSSGAVDX2Z1S33eWk',
    appId: '1:80359379857:web:f16c0d43f200209ba74030',
    messagingSenderId: '80359379857',
    projectId: 'my-pomodoro-b5569',
    authDomain: 'my-pomodoro-b5569.firebaseapp.com',
    storageBucket: 'my-pomodoro-b5569.firebasestorage.app',
    measurementId: 'G-LQTS12FFL7',
  );

}